BoxLayoutExample:

<BoxLayoutExample>:
    orientation: "vertical"
    Button:
        text: "A"
    Button:
        text: "B"
    Button:
        text: "B"

<MainWidget>:
    Button:
        text: "Hello"
        size: "100dp", "80dp"
        pos: "100dp","200dp"
        color: 0, 0, 1, 1
    Label:
        text: "Hello2"
        size: "40dp", "40dp"
        pos: "200dp","200dp"
        color: 1, 0, 0, 1

